title: Clara Lee
author: Clara Lee
email: clara.tung.lee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Email | clara.tung.lee@gmail.com <br/>
  Personal IG | @claraa_lee<br/>
  Bullet Journal IG | @journalsbyclara<br/>
  Facebook | @claraxlee<br/>
  Github | @7claralee<br/>
  
instagram_username: claraa_lee
github_username:  7claralee # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-architect
